spring.application.name=auth-service

server.port=8082

user.service.url=http://user-service:8081

jwt.secret=qwerty1234567890qwerty1234567890
jwt.expiration=3600000

logging.level.org.springframework.security=DEBUG
