
services:

  users-db:
    image: postgres:17
    container_name: users-db
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user_service
      POSTGRES_PASSWORD: user_service_pass
    ports:
      - "5433:5432"
    volumes:
      - users_data:/var/lib/postgresql/data

  accounts-db:
    image: postgres:17
    container_name: accounts-db
    environment:
      POSTGRES_DB: account_db
      POSTGRES_USER: account_service
      POSTGRES_PASSWORD: account_service_pass
    ports:
      - "5434:5432"
    volumes:
      - accounts_data:/var/lib/postgresql/data

  user-service:
    build: ./user-service
    container_name: user-service
    depends_on:
      - users-db
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/user_db
      SPRING_DATASOURCE_USERNAME: user_service
      SPRING_DATASOURCE_PASSWORD: user_service_pass

  auth-service:
    build: ./auth-service
    container_name: auth-service
    depends_on:
      - user-service
    ports:
      - "8082:8080"
    environment:
      USER_SERVICE_URL: http://user-service:8080

  account-service:
    build: ./account-service
    container_name: account-service
    depends_on:
      - accounts-db
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://accounts-db:5432/accounts_db
      SPRING_DATASOURCE_USERNAME: account_service
      SPRING_DATASOURCE_PASSWORD: account_service_pass

volumes:
  users_data:
  accounts_data: