spring.application.name=account-service

spring.datasource.url: jdbc:postgresql://account-db:5432/account_db
spring.datasource.username: account_service
spring.datasource.password: account_service_pass


# Endereço do Broker
spring.kafka.bootstrap-servers=kafka:9092

# Producer Configs
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Melhora a confiabilidade (Garante que o Broker confirmou o recebimento)
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3

# Configurações adicionais de JSON
spring.kafka.producer.properties.spring.json.add.type.headers=false


spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

