spring.application.name=account-service

spring.datasource.url: jdbc:postgresql://account-db:5432/account_db
spring.datasource.username: account_service
spring.datasource.password: account_service_pass

spring.kafka.bootstrap-servers: kafka:9092


spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

