version: '3.8'

services:

  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user_service
      POSTGRES_PASSWORD: user_service_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    container_name: user-service
    depends_on:
      - postgres
    ports:
      - "8080:8081"
volumes:
  postgres_data:

